[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "auth-service"
version = "0.2.0"
description = "Authentication microservice"
requires-python = ">=3.9"
dependencies = ["core-logger"]

[tool.setuptools.packages.find]
where = ["src"]
